export const configKeys = {
  6: [
    'mswPath',
    'miragePath',
    'hookPath',
    'dataPath',
    'funcsPath',
    'assetImagesPath',
    'assetFontsPath',
    'assetMiscPath',
    'contextPath',
    'reduxActionPath',
    'reduxStorePath',
    'reduxReducerPath',
    'zustandStoresPath',
    'localesPath',
    'typesPath',
    'components',
  ],
}
